apiVersion: v1
kind: Service
metadata:
  namespace: grpc-cluster
  name: grpc-cluster
  labels:
    app: grpc-cluster
spec:
  selector:
    app: grpc-cluster
  clusterIP: None
  ports:
  - port: 9010
    targetPort: 9010
    name: grpc
    protocol: TCP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: grpc-cluster
  name: grpc-cluster
spec:
  serviceName: "grpc-cluster"
  replicas: 2
  selector:
    matchLabels:
      app: grpc-cluster
  template:
    metadata:
      labels:
        app: grpc-cluster
      annotations:
        forceRestartcounter: "3"
    spec:
      containers:
        - name: grpc-cluster
          image: docker.flame.org/library/grpc-cluster:latest
          ports:
            - containerPort: 9010
              name: grpc
          env:
            - name: POD_IPS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIPs
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
