apiVersion: v1
kind: Service
metadata:
  namespace: grpc-cluster
  name: grpc-cluster
  labels:
    app: grpc-cluster
spec:
  selector:
    app: grpc-cluster
  clusterIP: None
  ports:
  - port: 9010
    targetPort: 9010
    name: grpc
    protocol: TCP
  - port: 9102
    targetPort: 9102
    name: metrics
    protocol: TCP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: grpc-cluster
  name: grpc-cluster
spec:
  serviceName: "grpc-cluster"
  replicas: 4
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: grpc-cluster
  template:
    metadata:
      labels:
        app: grpc-cluster
      annotations:
        forceRestartcounter: "14"
    spec:
      containers:
        - name: grpc-cluster
          image: docker.flame.org/library/grpc-cluster:latest
          ports:
            - containerPort: 9010
              name: grpc
            - containerPort: 9102
              name: metrics
          env:
            - name: POD_IPS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIPs
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
